name: frontend
channels:
  - conda-forge
dependencies:
  - matplotlib=3.7.1
  - opencv=4.7.0
  - pip=23.0.1
  - python=3.11.3
  - streamlit=1.9.0
  - requests
  - pip:
    - streamlit-drawable-canvas==0.9.2
