name: ml-app
channels:
  - conda-forge
dependencies:
  - fastapi=0.81.0
  - uvicorn=0.18.3
  - tensorflow=2.9.1
  - python=3.10.6
  - pip=22.2.2
  - pip:
    - opencv-python==4.6.0.66
    - streamlit==1.12.2
    - streamlit-drawable-canvas==0.9.1
